---
title: "HW6_GR5206"
author: "Tianchen Wang / tw2665"
date: "2018/11/20"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW6

### Part 1
\(f(x) = \frac{1}{\pi (1+x^2)} \\
F(x) = \frac{1}{\pi}tan^{-1}(x) + \frac{1}{2}  \\
F^{-1}(x) = tan(\pi(x-\frac{1}{2}))\)
Here we should add c = 1/2 after F(x) is because F, as a cdf need to be between 0 and 1.
```{r}
set.seed(0)

F.inverse <- function(u){
  tan(pi*(u-1/2))
}
cauchy.sim <- function(n){
  u <- runif(n)
  F.inverse(u)
}
cauchy.sim(10)
cauchy.draws <- cauchy.sim(1000)
{
  hist(cauchy.draws, probability = TRUE, breaks = 200)
  x <- seq(-800, 300, 1)
  lines(x, 1/pi*(1/(1+x^2)), col = "red")
}


```

### Part 2
### Problem 2
```{r}
# 4
f <- function(x){
  ifelse(-1 < x & x < 2, 1/9*(4-x^2), 0)
}

curve(f, -3, 3, n = 1000, main = "f(x) on [-3,3]")
x <- runif(1000, min = -3, max = 3)
y <- runif(1000, min = 0, max = 0.5)
{
plot(x, y, pch = ".")
lines(sort(x), f(sort(x)), col = "blue")
}

# 5
# here I set alpha = 1/f.max, but I didn't actually compute the maximum point of f(x)
f.max <- 4/9
alpha <- 1/f.max * 3
e <- function(x){
  ifelse((x < -1 | x > 2), Inf, 1/3*alpha)
}

# 6 & 7
n.samps <- 10000
n <- 0
f.draws <- numeric(n.samps)
while (n < n.samps){
  y <- runif(1, -1, 2)
  u <- runif(1)
  if (u < f(y)/e(y)){
    n <- n + 1
    f.draws[n] <- y
  }
 
} 
head(f.draws)
{
  hist(f.draws, probability = TRUE, xlab = "f.draws", ylab = "probability",
       main = "Histogram of the given density function")
  lines(seq(-1, 2, 0.01), f(seq(-1, 2, 0.01)), lty = 2, col = "red")
}

```

### Problem 3
```{r}
# 8
f <- function(x){
  1/sqrt(2*pi)*exp(-1/2*x^2)
}
curve(f, -5, 5, n = 1000, main = "Plot of f")

# 9
g <- function(x){
  (1/pi)*(1/(1+x^2))
}
e <- function(x, alpha = 1){
  g(x)/alpha
}

# 10
alpha = 0.6
{
  curve(f, -10, 10, n = 1000, main = "Plot of f")
  lines(seq(-10,10, 0.1), e(seq(-10,10, 0.1), alpha), col = "red")
}
all(e(seq(-10,10, 0.1), alpha) >= f(seq(-10,10, 0.1)))

# 11
normal.sim <- function(n.samps, method = "Accpet-Reject"){
  n <- 0
  draws <- numeric(n.samps)
  if (method == "Accpet-Reject"){
    while(n < n.samps){
      u <- runif(1)
      y <- rnorm(1)
      if(u < f(y)/e(y)){
        n <- n + 1
        draws[n] <- y
      }
    }
  }
  if (method == "Inverse"){
    u <- runif(n.samps)
    draws <- dnorm(u)
  }
  return(draws)
}
normal.sim(10)

# 12
normal.draws <- normal.sim(10000)
{
  hist(normal.draws, probability = TRUE)
  lines(seq(-3, 3, 0.1), f(seq(-3, 3, 0.1)), lty = 2, col = "red")
}

```

### Part 3
```{r}
# 13
x <- 5 
n <- 1
x.vals <- NULL
x.vals[1] <- x
while(x > 0){
  r <- runif(1, -2, 1)
  x <- x + r
  n <- n + 1
  x.vals[n] <- x
}
x.vals = x.vals[1: length(x.vals) - 1]
x.vals

# 14
plot(x = 1:length(x.vals), y = x.vals, type = "o",
     xlab = "iteration number", ylab = "x value")

# 15
random.walk <- function(x.start = 5, plot.walk = TRUE){
  n <- 1
  x.vals <- NULL
  x.vals[1] <- x.start
  while(x.start > 0){
    r <- runif(1, -2, 1)
    x.start <- x.start + r
    n <- n + 1
    x.vals[n] <- x.start
  }
  x.vals = x.vals[1: length(x.vals) - 1]
  if(plot.walk == TRUE){
    plot(x = 1:length(x.vals), y = x.vals, type = "o",
         xlab = "iteration number", ylab = "x value")
  }
  return(list(x.vals = x.vals, num.steps = length(x.vals) - 1))
}
random.walk()
random.walk(10, FALSE)

# 16
nums <- NULL
for(i in 1:10000){
  nums[i] <- random.walk(plot.walk =  FALSE)$num.steps
}
mean(nums)

# 17
random.walk <- function(x.start = 5, plot.walk = TRUE, seed = NULL){
  if(!is.null(seed)){
    set.seed(seed)
  }
  n <- 1
  x.vals <- NULL
  x.vals[1] <- x.start
  while(x.start > 0){
    r <- runif(1, -2, 1)
    x.start <- x.start + r
    n <- n + 1
    x.vals[n] <- x.start
  }
  x.vals = x.vals[1: length(x.vals) - 1]
  if(plot.walk == TRUE){
    plot(x = 1:length(x.vals), y = x.vals, type = "o",
         xlab = "iteration number", ylab = "x value")
  }
  return(list(x.vals = x.vals, num.steps = length(x.vals) - 1))
}
random.walk()
random.walk()
random.walk(seed = 33, plot.walk = FALSE)
random.walk(seed = 33, plot.walk = FALSE)
```

### Part 4
```{r}
# 18
g <- function(x){
  return(sqrt(1-x^2))
}

{
  par(pty = "s")
  plot(seq(0,1,.01),g(seq(0,1,.01)),type="l",col="purple")
}

# 19
1/4*pi

# 20
N <- 10000
x <- runif(N)
y <- runif(N)
approx <- sum(y < g(x))/N
approx
cat("difference b/t true value and approximate value", abs(1/4*pi - approx))
```

